github.com:
    users:
        coding4beginner:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: coding4beginner
